/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-secondary-fixed-variant": "#004f53",
        "on-secondary-container": "#1b6d71",
        "surface": "#fcf9f7",
        "surface-container-lowest": "#ffffff",
        "on-secondary-fixed": "#002021",
        "on-surface": "#1b1c1b",
        "error": "#ba1a1a",
        "primary-container": "#b9573e",
        "inverse-on-surface": "#f3f0ee",
        "primary": "#9a4028",
        "on-primary-fixed": "#3c0800",
        "surface-variant": "#e5e2e0",
        "inverse-surface": "#31302f",
        "on-error": "#ffffff",
        "on-secondary": "#ffffff",
        "secondary-fixed-dim": "#8ad3d7",
        "secondary-fixed": "#a6eff3",
        "on-tertiary": "#ffffff",
        "surface-tint": "#9d422b",
        "on-primary-container": "#fffbff",
        "on-tertiary-container": "#fffbff",
        "surface-bright": "#fcf9f7",
        "secondary": "#14696d",
        "on-tertiary-fixed": "#261a00",
        "inverse-primary": "#ffb4a2",
        "surface-container-high": "#eae8e6",
        "tertiary": "#765700",
        "surface-container-highest": "#e5e2e0",
        "on-surface-variant": "#56423d",
        "secondary-container": "#a3ecf0",
        "on-error-container": "#93000a",
        "on-primary-fixed-variant": "#7e2b16",
        "outline-variant": "#dcc0ba",
        "tertiary-fixed-dim": "#f6be39",
        "tertiary-container": "#956e00",
        "surface-container-low": "#f6f3f1",
        "surface-dim": "#dcd9d8",
        "background": "#fcf9f7",
        "primary-fixed-dim": "#ffb4a2",
        "primary-fixed": "#ffdbd2",
        "on-background": "#1b1c1b",
        "outline": "#89726c",
        "on-primary": "#ffffff",
        "surface-container": "#f0edeb",
        "error-container": "#ffdad6",
        "tertiary-fixed": "#ffdfa0",
        "on-tertiary-fixed-variant": "#5c4300",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      fontFamily: {
        headline: ["Manrope", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
      },
      keyframes: {
        pulse_glow: {
          "0%, 100%": { boxShadow: "0 0 0 0 rgba(154, 64, 40, 0.4)" },
          "50%": { boxShadow: "0 0 0 12px rgba(154, 64, 40, 0)" },
        },
        typing_bounce: {
          "0%, 100%": { transform: "translateY(0)" },
          "50%": { transform: "translateY(-4px)" },
        },
      },
      animation: {
        "pulse-glow": "pulse_glow 2s ease-in-out infinite",
        "typing-1": "typing_bounce 1.2s ease-in-out infinite",
        "typing-2": "typing_bounce 1.2s ease-in-out 0.15s infinite",
        "typing-3": "typing_bounce 1.2s ease-in-out 0.3s infinite",
      },
    },
  },
  plugins: [],
}
