server.port=8080
spring.application.name=clinica

# Gemini
gemini.api.key=${GEMINI_API_KEY:}
gemini.model=gemini-1.5-flash
gemini.api.base-url=https://generativelanguage.googleapis.com/v1beta/models

# HRSA
hrsa.api.base-url=https://findahealthcenter.hrsa.gov
hrsa.default.radius=10
